export const NETWORK_ERROR_CODES = [
  "ERR_NAME_NOT_RESOLVED",
  "ERR_NETWORK",
  "ERR_INTERNET_DISCONNECTED",
  "ERR_CONNECTION_REFUSED",
  "ERR_CONNECTION_TIMED_OUT",
  "ENOTFOUND",
  "ECONNREFUSED",
  "ETIMEDOUT",
];
